version: "3.7"

services:
  cors_anywhere:
    image: ${SWARMLET_REGISTRY}/cors-anywhere
    build: .
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.cors-anywhere.loadbalancer.server.port=8000
        - traefik.http.routers.cors-anywhere.rule=Host(`cors-anywhere.edmondchuc.com`)
        - traefik.http.routers.cors-anywhere.entrypoints=http,https
        - traefik.http.routers.cors-anywhere.middlewares=redirect@file

networks:
  traefik-public:
    external: true
